[package]
name = "xtask"
version = "0.1.0"
edition = "2021"


[dependencies]
anyhow = "1.0"
image = { version = "0.25", default-features = false, features = ["png"] }
ico = "0.4.0"
which = "8.0.0"
dirs = "6.0.0"
walkdir = "2.5.0"
resvg = "0.45.1"
oxipng = "9.1.5"